language: go

go:
  - 1.8.1

before_install:
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci

os:
  - linux
  - osx

install:
  - go get -v

script:
  - go build -v .
  - go test -v ./

notifications:
  email:
    - badr.adnaan@gmail.com